# Generated by Django 4.0.1 on 2022-01-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remains',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
